### ISSUE TITLE
About Pconsc4 

### ISSUE THREAD

**Issue by qwe1997** [595693085/DGraphDTA#2]
Thanks for sharing codes and data for the article.I have tried to install all dependencies in this program but I failed to install Pconsc4 and the error is shown in the following:

 ERROR: Command errored out with exit status 1:
     command: 'c:\anaconda3\envs\dgraphdta\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\11956\\AppData\\Local\\Temp\\pip-install-gxcrzxw5\\pygaussdca\\setup.py'"'"'; __file__='"'"'C:\\Users\\11956\\AppData\\Local\\Temp\\pip-install-gxcrzxw5\\pygaussdca\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\11956\AppData\Local\Temp\pip-pip-egg-info-0tit5l98'
         cwd: C:\Users\11956\AppData\Local\Temp\pip-install-gxcrzxw5\pygaussdca\
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\11956\AppData\Local\Temp\pip-install-gxcrzxw5\pygaussdca\setup.py", line 10, in <module>
        from pythran import PythranExtension
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\__init__.py", line 39, in <module>
        from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\toolchain.py", line 6, in <module>
        from pythran.backend import Cxx, Python
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\backend.py", line 8, in <module>
        from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\analyses\__init__.py", line 12, in <module>
        from .aliases import Aliases, StrictAliases
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\analyses\aliases.py", line 6, in <module>
        from pythran.syntax import PythranSyntaxError
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\syntax.py", line 7, in <module>
        from pythran.tables import MODULES
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\tables.py", line 175, in <module>
        BINARY_UFUNC = {"accumulate": FunctionIntr()}
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\intrinsic.py", line 93, in __init__
        super(FunctionIntr, self).__init__(**kwargs)
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\pythran\intrinsic.py", line 57, in __init__
        [to_ast(d) for d in kwargs.get('defaults', [])])
      File "c:\anaconda3\envs\dgraphdta\lib\site-packages\gast\gast.py", line 19, in create_node
        format(Name, nbparam, len(Fields))
    AssertionError: Bad argument number for arguments: 6, expecting 7
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

So how to deal with this problem?What should I do for the data preparation if I want to use my own datasets?

**Comment by qwe1997** [comment]
I just solved the problem,because I can not install pyGaussDCA so I failed to install Pconsc4 .Here is my environment:
python 3.7 &  Pythran 0.9.5 & gast 0.3 & beniget 0.2
Don't use the newest gast and beniget or you will failed to install Pconsc4

**Comment by PuYuQian** [comment]
Thanks for your help.
